### ISSUE TITLE
Can't move issues with more than 35 comments

### ISSUE THREAD

**Issue by boelle** [google/github-issue-mover#114]
i get the same errors as in #11 when i try to move issues with more than 35 comments...

and i have yet to figure how to setup the app as mentioned in the last post before me

**Comment by steveswinsburg** [comment]
I also had this problem.

**Comment by sils1297** [comment]
Interesting number... if it were thirty I'd bet it was because of GitHub API paging...

**Comment by GeoffreyBooth** [comment]
I have this issue as well, exactly 35. Then if I try to post another comment manually I get an error about having posted a comment too recently. I suppose we’re hitting some API limit, of the number of comments within a short period? If so, the solution is simple: just space out the comment postings as needed to avoid hitting the limit.

**Comment by GeoffreyBooth** [comment]
So after 35 comments in a short period, you need to wait a minute before posting another comment (as of 2018-02-19) due to GitHub’s [abuse rate limits](https://developer.github.com/v3/#abuse-rate-limits). @nicolasgarnier it would be nice if `github-issue-mover` implemented support for automatically waiting whenever a 403 (rate limit) is returned from the GitHub API. See https://github.com/buildo/gh-issue-mover/pull/3 for an example.
