### ISSUE TITLE
please stop

### ISSUE THREAD

**Issue by contra** [google/github-issue-mover#40]
github bots are evil, please stop doing this. you are spamming every issue you touch to shit.

for reference:

https://github.com/joyent/node/issues/9322
https://github.com/joyent/node/issues/9323

please please stop. just stop. please. fucking hell my notifications are going insane.

**Comment by contra** [comment]
@nicolasgarnier @kevmoo

**Comment by nicolasgarnier** [comment]
There are no bots involved with the github-issue-mover it's an online tool that you have to **manually** use here: https://github-issue-mover.appspot.com

It seems a use called @fcdwg is using the tool to move issues from joyent/node to google/github-issue-mover. He is doing this manually and it's annoying me as much as you :D (because I have to clean my issue list too.

If this continues I'll add a ban list into the tool and add @fcdwg to it.

**Comment by ChALkeR** [comment]
I sent an abuse report to GitHub regarding @fcdwg.
He has no other contributions except for that spam reports: https://github.com/fcdwg?tab=contributions&period=monthly

**Comment by nicolasgarnier** [comment]
Thanks @ChALkeR!
